version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - wget https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz
      - tar xzf Python-2.7.16.tgz
      - cd Python-2.7.16
      - /usr/local/bin/python2.7 -V
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy -s stag

  post_build:
    commands:
#      - aws s3 rm s3://terravirtua-lts-deploy-prod --recursive
